### ISSUE TITLE
Update to latest cargo API encounters breaking changes

### ISSUE THREAD

**Issue by macs-overdrv** [cargo2nix/cargo2nix#110]
Updating the cargo dependency is mostly straightforward except changes to one method cargo2nix uses, `cargo::ops::resolve_ws_with_opts` because of the new arguments it accepts

https://docs.rs/cargo/0.44.0/cargo/ops/fn.resolve_ws_with_opts.html
https://docs.rs/cargo/0.41.0/cargo/ops/fn.resolve_ws_with_opts.html

Most of the changes happened in this PR
https://github.com/rust-lang/cargo/pull/7820

Here's internal usages of those arguments:
https://github.com/rust-lang/cargo/search?q=HasDevUnits&unscoped_q=HasDevUnits
https://github.com/rust-lang/cargo/search?q=CompileKind&unscoped_q=CompileKind

I'm filing this issue because at a minimum, the API changes will block cargo2nix from using newer cargo features, meaning some projects with recent cargo features cannot be built with current cargo2nix

**Comment by ebkalderon** [comment]
Thanks for reporting the issue, @macs-overdrv! ❤️

I remember seeing that PR around the the time that it had been merged, and I don't know if there is an easy solution to this. In particular, ignoring targets that aren't being built and not unifying features between normal, build, and dev dependencies break certain fundamental assumptions about how `cargo2nix` works and how we perform feature resolution.

CC @trha

**Comment by macs-overdrv** [comment]
> In particular, ignoring targets that aren't being built and not unifying features between normal, build, and dev dependencies

The dev units issue appears to have a simple workaround.  [If dev units are always turned on](https://github.com/tenx-tech/cargo2nix/pull/111/commits/ac81eb2031ca8d715052cf67793a813309ea103d), the resulting `packageFun` might be a little bit heavy, but not broken.  Alternatively, since dev units are not expected to be useful for distribution, the role of cargo2nix, there are also strong arguments in favor of defaulting to excluding dev units.

The [signature in newer cargo](https://github.com/tenx-tech/cargo2nix/pull/111/files#diff-639fbc4ef05b315af92b4d836c31b023L299-R313) strongly suggests target-dependent features were added, which the newer cargo library can evaluate correctly.  However, the output of a package function for a _single_ target would only cover one possible result from cargo.

How does cross compiling currently work?  Is it even aware of the target when resolving features?  If it's not aware of the target, then it's safe to say that target-dependent features did not exist up until newer cargo?  The implication is that the current cargo2nix is starting in a broken state WRT target-dependent features.

If current cargo2nix is broken for those features, I'm not sure what the shortest path is.  At first glance it seems like either the Cargo.nix needs to be parameterized over the target or broken into several Cargo.nix's that are selected based on the target (this would be closer to what I expect as a fast or interim workaround).

As a first step, I propose we fast track the cargo dependency update so that **other** modern cargo features will just work while the target dependency issue is worked out.  There are many features beside dev units and target-dependent features that the older version of cargo can't understand at all.  The cases that newer cargo introduce are cases that older cargo and therefore cargo2nix are just blissfully unaware of.

As interim workaround I propose adding  `--target=<target>` and `--hasdevunits` as an argument to Cargo2nix so that [`HasDevUnits`](https://github.com/tenx-tech/cargo2nix/pull/111/commits/ac81eb2031ca8d715052cf67793a813309ea103d) and [`CompileKind` and `RustcTargetData`](https://github.com/tenx-tech/cargo2nix/pull/111/commits/0440522465937f4989d94c8506e992c2520e00ed) can be forced by the user, meaning they can generate whichever `packageFun` they need, perhaps several, while the issues are more fully worked out.

**Comment by ebkalderon** [comment]
Indeed, you're correct. Target-specific features haven't existed in Cargo since landing recently in `nightly` with https://github.com/rust-lang/cargo/issues/1197. Since this feature isn't in stable, `cargo2nix` isn't in a broken state and feature resolution currently works as expected (including cross-compilation). However, it will be considered broken as soon as this feature is officially stabilized.

Definitely agree that we should fast-track the Cargo dependency update so we don't block other future changes and improvements to Cargo. 👍 I'm not fully convinced that `--target=<target>` would be a suitable workaround, though. The `Cargo.nix` is supposed to encode the feature and dependency selection logic for all supported targets, regardless of the current host platform.

Any thoughts on how to proceed with this, @trha @eupn @antigravityla?

**Comment by macs-overdrv** [comment]
> The Cargo.nix is supposed to encode the feature and dependency selection logic for all supported targets, regardless of the current host platform.

I'm going to take a look at the definition and see if it doesn't look easy to pass-through into the `packageFun`.  This might mean looking at the toml / lock directly instead of letting cargo tell us which items have target-dependent features.

**Comment by ebkalderon** [comment]
Looks like `cargo` 0.46.0 has added a `ForceAllTargets::{Yes,No}` argument to `resolve_ws_with_opts()`, which appears to disable the per-target filtering and restores the old behavior ([docs.rs](https://docs.rs/cargo/0.46.0/cargo/ops/fn.resolve_ws_with_opts.html))! Will have to try it to see if everything still builds successfully.
