### ISSUE TITLE
target_arch match in Cargo.nix

### ISSUE THREAD

**Issue by giacomocariello** [cargo2nix/cargo2nix#144]
target_arch in Cargo.toml dependencies is converted to a comparison with hostPlatform.parsed.cpu.name, which is invalid for hostPlatforms whose arch name differs from rust expected naming, like "armv6l" or "armv7l".

Some kind of conversion from hostPlatform should be applied before passing as argument to packageFun.

**Comment by psionic-k** [comment]
I want to pick this up.   Can you provide some more information about a concrete case for me to look at?  I was going to add some cross-compiling to CI at the same time

**Comment by psionic-k** [comment]
What I'm gathering is that we need to be able to align between any possible first component in `rustc --print target-list` such as `thumbv7neon-unknown-linux-musleabihf`

Trouble is that thumb is not in the list of cpuTypes
https://github.com/NixOS/nixpkgs/blob/fb875dcf6fbadafb41c64d9f4e1ef056f127bcb3/lib/systems/parse.nix#L69-L123

Probably some combination of features & arch are necessary to build the map.  Might try to adopt a more open solution that lets people break things but doesn't restrict them to the types listed in cpuTypes

**Comment by psionic-k** [comment]
I believe this got fixed in https://github.com/cargo2nix/cargo2nix/commit/850a9f1906d35b9695a9e5db20d604032cb133ad

Please re-open if you still have an issue
