### ISSUE TITLE
Example '1-hello-world' not working

### ISSUE THREAD

**Issue by zzeroo** [cargo2nix/cargo2nix#162]
Hi I try to build the example '1-hello-world'. 

I follow the README instructions and get this error on `nix-build`

```bash
nix-build
error: cannot update ref 'refs/heads/v0.9.0': trying to write non-commit object 50b861a95e0e69edddb651883a4df0b5286a0883 to branch 'refs/heads/v0.9.0'
error: program 'git' failed with exit code 1
```

```bash
# default.nix
{
  system ? builtins.currentSystem,
  nixpkgsMozilla ? builtins.fetchGit {
    url = https://github.com/mozilla/nixpkgs-mozilla;
    rev = "50bae918794d3c283aeb335b209efd71e75e3954";
  },
  cargo2nix ? builtins.fetchGit {
    url = https://github.com/cargo2nix/cargo2nix;
    ref = "v0.9.0";
  },
}:
let
  rustOverlay = import "${nixpkgsMozilla}/rust-overlay.nix";
  cargo2nixOverlay = import "${cargo2nix}/overlay";

  pkgs = import <nixpkgs> {
    inherit system;
    overlays = [ rustOverlay cargo2nixOverlay ];
  };

  rustPkgs = pkgs.rustBuilder.makePackageSet' {
    rustChannel = "stable";
    packageFun = import ./Cargo.nix;
  };
in
  rustPkgs.workspace.hello-world {}
```

[Cargo.nix.TXT](https://github.com/cargo2nix/cargo2nix/files/5719851/Cargo.nix.TXT)

[Cargo.toml.TXT](https://github.com/cargo2nix/cargo2nix/files/5719853/Cargo.toml.TXT)

**Comment by psionic-k** [comment]
Pin rev to 4bbd3137ff1422ef3565748eae33efe6e2ffbf39, the 0.9.0 tag.  Don't know why that says ref.  Open a PR if you beat me to it :) 

In CI we build by passing in an attribute that overrides `cargo2nix` with the version in the branch being CI'd, therefore this fetchGit is never evaluated (lazily)
