### ISSUE TITLE
Nondeterministic list order in Cargo.nix

### ISSUE THREAD

**Issue by psionic-k** [cargo2nix/cargo2nix#183]
A case was discovered where cargo2nix would generate Cargo.nix output with differing list orders.  There's no expected consequence to repeatable evaluation, but it's a reasonable expectation to maintain bijection between the Cargo.lock and the Cargo.nix. 

Reported by @TylerRichie

**Comment by ebkalderon** [comment]
Good call! I'm still marking this issue as a bug, despite causing no harm, since producing output that's not binary reproducible seems somewhat like an oversight to me. Perhaps we should sort our list of entries by name before writing them to the `Cargo.nix` to keep the results consistent?

**Comment by ollie-etl** [comment]
This is an annoyance- its adds significantly to diff noise

**Comment by psionic-k** [comment]
I either imagined that @trha fixed this or I wrote the changes into a driveby fix.  Cannot find a commit for this issue.

No point talking about it.  If we know what list is needing a sort, just sort it and write a PR.

What I'm also not seeing is line noise in the updates to the Cargo.nix.  Marking closed.  If anyone can find a list that's out of order, please just add the sort and write a PR :cat2:
