### ISSUE TITLE
Add an example that uses extra build inputs

### ISSUE THREAD

**Issue by drozdziak1** [cargo2nix/cargo2nix#186]
I don't think any of the examples does that and I am honestly struggling to do that. What I'm really after is to see some `makeOverride` usage in an example.

**Comment by ollie-etl** [comment]
Whats missing from [overrides.nix](https://github.com/cargo2nix/cargo2nix/blob/14da69bbe13c61f809fe9e0d979cdd8bf6563fcf/overlay/overrides.nix)? This is documented in the readme as the place to look.

the pattern in i.e [this override](https://github.com/cargo2nix/cargo2nix/blob/14da69bbe13c61f809fe9e0d979cdd8bf6563fcf/overlay/overrides.nix#L105) is a pretty good example of an extra buildinput

**Comment by ollie-etl** [comment]
for an absolutely concrete example, how about the following,. This assumes you've a workspace, with all your crates in the `./crates` subfolder.

*default.nix*
```nix
{pkgs}:

let
  rustPkgs = pkgs.rustBuilder.makePackageSet' rec {
    packageFun = import ./Cargo.nix;
    packageOverrides = pkgs:
      pkgs.rustBuilder.overrides.all
      ++ (import ./sys-crates.nix { inherit pkgs; });
  };

  crates = pkgs.lib.mapAttrsToList (n: _: n)
    (pkgs.lib.filterAttrs (n: v: v == "directory") (builtins.readDir ./crates));

in pkgs.lib.genAttrs crates (n: rustPkgs.workspace."${n}" { });

```

*sys-crates.nix*

```nix
{pkgs}:
let 
   overrides = {
     # declare your set of overrides here
      foo = makeOverride {
        name = "foo";
        overrideAttrs = drv: {
          propogatedNativeBuildInputs = drv.propagatedNativeBuildInputs or [ ] ++ [ pkgs.openssl.dev pkgs.zlib.dev ];
        };
      };

      bar = makeOverride {
        name = "bar";
        overrideAttrs = drv: {
          propogatedNativeBuildInputs = drv.propagatedNativeBuildInputs or [ ] ++ [ pkgs.openssl.dev pkgs.zlib.dev ];
        };
      };

   };
in (map (key: pkgs.lib.getAttr key overrides) (builtins.attrNames overrides))
```

**Comment by drozdziak1** [comment]
Hey, thanks for getting back to me. I believe I did a lousy job reading the `README.md` - everything that I need to know is alsoexplained in `Common issues`. Thanks for the example.
