### ISSUE TITLE
dangling path

### ISSUE THREAD

**Issue by mhuesch** [cargo2nix/cargo2nix#202]
hi!

thx for this project, it has been very helpful for scaffolding my projects 🙏

I noticed what seems to be a dangling path in the overlay here: https://github.com/cargo2nix/cargo2nix/blob/381f9760d471bc07925d13ac924b0a1bb86d78a5/overlay/default.nix

see example to reproduce:

```
vayu :: /tmp/cargo2nix-test » bat flake.nix
───────┬──────────────────────────────────────────────────────────────────────────────────────────────
       │ File: flake.nix
───────┼──────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   description = "cargo2nix-test";
   3   │
   4   │   inputs = {
   5   │     nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
   6   │     flake-utils.url = "github:numtide/flake-utils";
   7   │     cargo2nix.url = "github:cargo2nix/cargo2nix/feature/add-basic-flake-support";
   8   │   };
   9   │
  10   │   outputs = { self, nixpkgs, flake-utils, cargo2nix, ... }:
  11   │     flake-utils.lib.eachDefaultSystem (system:
  12   │       let
  13   │         overlays = [
  14   │           (import "${cargo2nix}/overlay")
  15   │         ];
  16   │         pkgs = import nixpkgs {
  17   │           inherit system overlays;
  18   │         };
  19   │       in
  20   │       {
  21   │         defaultPackage =
  22   │           pkgs.rustBuilder.mkCrate;
  23   │       });
  24   │ }
───────┴──────────────────────────────────────────────────────────────────────────────────────────────
vayu :: /tmp/cargo2nix-test » nix build
error: getting status of '/nix/store/jk4sv25dglwi8j0d7bwxn0f7npshp7jq-source/overlay/crate.nix': No such file or directory
(use '--show-trace' to show detailed location information)
```

I'm using the flakes branch but it appears on `master` too.

**Comment by psionic-k** [comment]
What are you trying to build?  Might check release-0.9.1 but I suspect it's got the same issue.  A stripped down toml & lock  in addition to a Cargo.nix generated from them would be helpful.

**Comment by psionic-k** [comment]
I definitely can't proceed on this one without some more context.  No idea. :thinking:

**Comment by mhuesch** [comment]
hi, thx for the reply.

this is not actually something driven by a need I have, so perhaps that makes it a little goofy.

I just noticed that in the overlay, `rustBuilder.mkCrate` is defined as such: https://github.com/cargo2nix/cargo2nix/blob/cb135df8c3287a91f9fbcbe11fad358800a93a7c/overlay/default.nix#L9

but there doesn't seem to be a `crate.nix` file in the [`overlay` directory](https://github.com/cargo2nix/cargo2nix/tree/cb135df8c3287a91f9fbcbe11fad358800a93a7c/overlay).

so I made the above simplified example as a way to demonstrate that. I realize now that it was not actually as minimal as it could be, and wasn't explained very clearly.

still, am I right that `error: getting status of '/nix/store/jk4sv25dglwi8j0d7bwxn0f7npshp7jq-source/overlay/crate.nix': No such file or directory` indicates that the `crate.nix` file is indeed missing?

**Comment by mhuesch** [comment]
or perhaps that is a file that is supposed to be generated somehow and I didn't do that setup?

**Comment by psionic-k** [comment]
Oh!  My bad.  I didn't read your nix enough.  Indeed there is no crate.nix.   I'm removing this path.

https://github.com/cargo2nix/cargo2nix/pull/214/files#diff-b4c91c032921ee70c4610edb930fca6c05d52b337af2dc735bd8ed4f4ec75435L9

**Comment by mhuesch** [comment]
no worries. very cool, thanks! :rocket:
