### ISSUE TITLE
Non workspace path dependencies

### ISSUE THREAD

**Issue by omerbenamram** [cargo2nix/cargo2nix#207]
Hi - thanks for the work on this project :)

We're experimenting working in a monorepo where not all projects are in the same workspace.
We have rust projects referencing other local libraries by path.

```
├── framework
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── src
│   └── target
└── serv
    ├── Cargo.lock
    ├── Cargo.toml (has dependency `framework = ../framework")
    ├── src
    └── target
```

I've tried playing with `workspaceSrc` to try and include said lib crate, since `cargo2nix` seems to generate code to fetch local crates - 

When using `workspaceSrc = ../..`
```
serv on master [!+?] is 📦 v0.1.0 via 🦀 v1.56.1 
❯ nix build
warning: Git tree '/home/omer/Workspace/repo/serv' is dirty
error: access to path '/framework' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)

serv on master [!+?] is 📦 v0.1.0 via 🦀 v1.56.1 
❯ nix build --impure
warning: Git tree '/home/omer/Workspace/repo/serv' is dirty
error: getting status of '/framework': No such file or directory
(use '--show-trace' to show detailed location information)
```

when using `workspaceSrc = ./.` (default):
```
warning: Git tree '/home/omer/Workspace/nix_core/serv' is dirty
error: 'framework' is too short to be a valid store path
(use '--show-trace' to show detailed location information)
```

Is this something that would be possible under the current design of `crago2nix`? 

Thanks!

**Comment by omerbenamram** [comment]
This was actually because of a git messup with my minimized repo! This does work (and AFAIK `cargo2nix` is the only solution that supports this)

**Comment by psionic-k** [comment]
Can we close or is there still more to fix?

**Comment by omerbenamram** [comment]
It's fully working. Closing :)
