### ISSUE TITLE
Features may not match those enabled from workspace

### ISSUE THREAD

**Issue by psionic-k** [cargo2nix/cargo2nix#211]
Rust Analyzer winds up with both mimalloc and jemalloc enabled.  This was patched out by hand.  The greater problem is that features vanishing or appearing when switching from a direct cargo build to a nix build.  Features are very common, so this is very high priority.

**Comment by jrobsonchase** [comment]
Played around with it a bit and came up with a [minimal example](https://github.com/jrobsonchase/cargo2nix-features).

At first glance, it looks like `Cargo.nix` simply contains all features listed in `Cargo.toml`, where it should only have `default`. Not sure how deep the mismatch goes though. I'll see about testing some more complex scenarios.

**Comment by mhuesch** [comment]
I think I have run into this on a project. I would be open to contributing to a fix if I could be pointed in the right direction. I probably won't have time to dive into implementation until start of Jan tho.

**Comment by psionic-k** [comment]
>  I would be open to contributing to a fix if I could be pointed in the right direction

The features that wind up in Cargo.nix are the result of looking at Cargo.lock and root workspace manifests.  The `generate_cargo_nix` function is pretty readable:

https://github.com/cargo2nix/cargo2nix/blob/c9e80f390265ee982e24018a00111648e5b729be/src/main.rs#L175-L237

There were a few version updates to the cargo library that required some new arguments where I'm pretty sure people just shoveled in whatever variable was on hand or at least passed type checking.

There was some consternation around target-specific features because we don't know the target until in the nix build, meaning target-specific features need to translate into nix expressions in Cargo.nix (parameterizing over features)

> minimal example

This is gold. I'll take a shot at debugging this today

**Comment by psionic-k** [comment]
Detailed my path investigation for those wishing to get up to speed on translating cargo behavior -> nix expressions

1. Cargo.nix is output from [/templates/Cargo.tera]

2. The features in question are not optional in the Cargo.nix, so we can presume they were marked required

3. Commenting `simplify_optionality` in [/src/main.rs]  leads to the following change in Cargo.nix:

```diff
     features = builtins.concatLists [
-      [ "default" ]
-      [ "python" ]
+      (lib.optional (rootFeatures' ? "foo") "default")
+      (lib.optional (rootFeatures' ? "foo") "python")
     ];
```
So they are beginning as optional features and getting simplified.

5. Inside `generate_cargo_nix` we find that two functions that look like they update features, `mark_required` and `activate`

6.  Inside `mark_required`, commenting https://github.com/cargo2nix/cargo2nix/blob/master/src/main.rs#L324-L329 yields a diff with some full paths to the root features:

```
     features = builtins.concatLists [
-      [ "default" ]
-      [ "python" ]
+      (lib.optional (rootFeatures' ? "foo/default") "default")
+      (lib.optional (rootFeatures' ? "foo/python") "python")
     ];
```

### Okay So What do We Really Expect?

`foo/default` is always enabled because it's a default feature.  `foo/python` should be enabled only if it's a key of `rootFeatures` (because we specified it in `makePackageSet`.  The correct result would look pretty much like:

``` nix
     features = builtins.concatLists [
      [ "default" ]
      (lib.optional (rootFeatures' ? "python") "python")
     ];
```

Quickly grepping RustAnalyzer, we find that there are explicit default features, the same thing in this minimal example.  This increases suspicion of our default feature handling.

```text
./crates/limit/Cargo.toml
11:default = ["tracking"]
```

### New Edge Case

Any fix needs to work whenever `default = [ "python" ]`    So I run over and add some new features to the example toml.

```toml
[features]
default = ["python"]
python = []
elisp = [] # a new feature
```

This should give us Nix output like:


``` nix
     features = builtins.concatLists [
      [ "default" ]
      (lib.optional (rootFeatures' ? "default") "python")
      (lib.optional (rootFeatures' ? "elisp") "elisp")
     ];
```

Let's be sure cargo agrees with this idea of what features should be enabled:

```shell
cargo tree -e features -i foo
foo v0.1.0 (/home/satoshi/Desktop/positron/debug/cargo2nix-features)
├── foo feature "default" (command-line)
└── foo feature "python"
    └── foo feature "default" (command-line)
```

Looks to me like default is enabled (by not passing --no-default-features, so "command-line").  Default enables python and default, but not elisp.

### Towards a Fix

Close to a patch but taking a break.

Heavy commenting revealed that the features are already on the crates as they had been provided by cargo library.

It t looks like the logic to mark features as activated and then simplify them is unaware of any relationship between the features of the crate and the explicit default feature.  If there's a default, they would be activated by self at the top of the dependency tree.  The logic that simplifies might "simplify" features that need to have logic expressions.  Activating all the top-level crate features is wrong when there is a default.  I think that's also happening.

`rootFeatures` is calculated correctly:
https://github.com/jrobsonchase/cargo2nix-features/blob/main/Cargo.nix#L7

Only default is actually an enabled root feature.  Even after adding the edge case feature, only default is listed when I regenerated the Cargo.nix.  What's needed is to prevent simplification using the rootFeatures logic as basis.

**Comment by psionic-k** [comment]
This is a bit of a tangent.  I've long wanted to improve the architecture.

### The Problem Model

In terms of nixifying the actual build of outputs, the job of cargo2nix is to build each crate in isolation.

There's three broad categories of information that need to be transmitted when hand-building crates in isolation:

1.  Top level information - target, action (build? test?), top level feature flags?
2.  Linking information and rlibs up to dependents
3.  Feature and override information down to dependencies

That's basically it.  If you look at how most of this is done now, there's a lot of `jq` `remarshal` and `cargo` use in the build and install steps.  Information sent down counts as inputs.  Information propagated up, the linking information, theoretically just depends on the inputs.  That is how the dependencies are supposed to be pure & deterministic (non-deterministic macros or binary output is present and very evil #184)

Taking a good look at this hunk:

https://github.com/cargo2nix/cargo2nix/blob/master/overlay/mkcrate.nix#L202-L235

The overlay moves the original toml out of the way.  Therefore, any features we haven't sent in via nix will not be activated even if the toml would have activated them.

For target-specific and platform-specific dependencies (both interestingly collapse to a `hostPlatform` switch), we have to replicate the logic in nix expressions in the Cargo.nix:

```nix
    dependencies = {
      bitflags = rustPackages."registry+https://github.com/rust-lang/crates.io-index".bitflags."1.3.2" { inherit profileName; };
      libc = rustPackages."registry+https://github.com/rust-lang/crates.io-index".libc."0.2.107" { inherit profileName; };
      libgit2_sys = rustPackages."registry+https://github.com/rust-lang/crates.io-index".libgit2-sys."0.12.24+1.3.0" { inherit profileName; };
      log = rustPackages."registry+https://github.com/rust-lang/crates.io-index".log."0.4.14" { inherit profileName; };
      ${ if hostPlatform.isUnix && !(hostPlatform.parsed.kernel.name == "darwin") then "openssl_probe" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".openssl-probe."0.1.4" { inherit profileName; };
      ${ if hostPlatform.isUnix && !(hostPlatform.parsed.kernel.name == "darwin") then "openssl_sys" else null } = rustPackages."registry+https://github.com/rust-lang/crates.io-index".openssl-sys."0.9.70" { inherit profileName; };
      url = rustPackages."registry+https://github.com/rust-lang/crates.io-index".url."2.2.2" { inherit profileName; };
    };
``` 

I had started to consider farming more of this logic out to `cargo` by preserving more of the toml.  However, we have to decide at evaluation time what features will be enabled on dependencies.  If we decline to make this decision, we would have to run cargo on dependents to figure out what features they will request on dependencies.  This would make twice as many derivations, those going down the DAG and then back up the DAG.  The infection of impurity from top to bottom of the DAG would negate caching most of the time.

We can farm a little bit more out to cargo if we only calculate glue logic, how a feature included in `rootFeatures` can possibly affect downstream features.

If the generation of the synthetic toml then retained all feature expressions, the glue would still hold together for any combination of `rootFeatures`

A downward pass in evaluation would be allowable because often it will just evaluate to the same derivation, meaning no rebuild.

For now I think I'll just fix the bug :cat2:  What we're doing is sustainable enough except I worry about the feature unification logic that needs to change for certain cases.

I don't think cargo2nix has been updated fully for resolver2 yet:

> The version "2" resolver avoids unifying features in a few situations where that unification can be unwanted. The exact situations are described in the resolver chapter, but in short, it avoids unifying in these situations:
>
>    Features enabled on platform-specific dependencies for targets not currently being built are ignored.
>    Build-dependencies and proc-macros do not share features with normal dependencies.
>    Dev-dependencies do not activate features unless building a target that needs them (like tests or examples).

https://doc.rust-lang.org/cargo/reference/features.html#feature-resolver-version-2

**Comment by psionic-k** [comment]
After expansion in Cargo.nix, `baseFeatures'` becomes something like:

```nix
{
  base_db = <CODE>;  
  base_db/default = <CODE>; 
  cfg = <CODE>;  
  cfg/default = <CODE>
}
```

The head of each feature is added as a kind of pseudo feature to simplify expressions.  Whenever the mere inclusion of a crate activates a dependency's feature, it's enough to say `rootFeatures ? "foo"` instead of `rootFeatures ? foo/something`.  In fact, there is no `something` if the feature is set in `[dependencies]` and not as a result of feature transitivity.

The template and other code are perfectly capable of generating large or expressions.  See these examples from RustAnalyzer's Cargo.nix:

```nix
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "rust-analyzer") "force")
      (lib.optional (rootFeatures' ? "base_db" || rootFeatures' ? "cfg" || rootFeatures' ? "flycheck" || rootFeatures' ? "hir" || rootFeatures' ? "hir_def" || rootFeatures' ? "hir_expand" || rootFeatures' ? "hir_ty" || rootFeatures' ? "ide" || rootFeatures' ? "ide_assists" || rootFeatures' ? "ide_completion" || rootFeatures' ? "ide_db" || rootFeatures' ? "ide_diagnostics" || rootFeatures' ? "ide_ssr" || rootFeatures' ? "mbe" || rootFeatures' ? "proc_macro_api" || rootFeatures' ? "proc_macro_srv" || rootFeatures' ? "project_model" || rootFeatures' ? "rust-analyzer" || rootFeatures' ? "stdx" || rootFeatures' ? "syntax" || rootFeatures' ? "test_utils" || rootFeatures' ? "tt") "log")
    ];
```
So enabling the `log` feature is performed if _any_ of the keys listed are matched in `rootFeatures`

The user is able to pass in customized `rootFeatures` and this is why this whole system exists.  The logic has to encode any feature that is enabled as a result of a root package feature (or root package alone)...  The transitive features.

The thing is, on workspace crates, the features should never be simplified down because user-supplied `rootFeatures` can fine-tune everything, omitting `foo/default` and specifying any combination of specific `foo/*` features.

The use of the psuedo-features makes sense if the crate is what's enabling a feature on a dependency.  What doesn't make sense is reducing top level workspace feature expressions.

```toml
[features]
# Enables parallel processing support by enabling the "rayon" feature of jpeg-decoder.
parallel = ["jpeg-decoder/rayon"]
```

This kind of transitive feature dependency should give us expressions like:

```nix
  (lib.optional (`rootFeatures'?` "foo/parallel") "rayon")
```

In the features of the `jpeg-decoder` crate.

I think I know what work needs to be done, but I've supplied this light reading for anyone attempting to get up to speed on development.  These are the rough drafts for a README architecture section :cat2:

**Comment by psionic-k** [comment]
https://github.com/psionic-k/cargo2nix-features/blob/main/Cargo.toml

https://github.com/cargo2nix/cargo2nix/pull/224/commits/ad7a57d8ad4f07bb92ee2ac1f0e08a6359f24a69

This could have some side effects.  Both dependencies & features have optionality.  Need some sleep to properly read it all.

Pretty close.  Gotta get full features in the expressions since not one of those features is enabled when building with --no-default-features.  If `rootFeatures` doesn't include `foo/default` then default shouldn't be activated.

**Comment by psionic-k** [comment]
There are some blind spots in the existing system.  Here's a from-scratch design.

## Required features & deps

For each root crate, activate no features and resolve dependencies.  If they are active, mark them as activated by the root crate alone (not by its features)
if any dependency or feature is activated n times where n = root_crate_n, then mark it as required.  This removes all logic in the Cargo.nix since the feature / dependency does NOT depend on the feature state or which root package gets built.

## Activated features & deps

This is the missing behavior needed to fix this issue

For each root crate, resolve dependencies.  Save deps.
For each root crate feature, resolve dependencies.  If dep activated, mark activated_by (root_crate, feature)
These will render in the Cargo.nix as a list of logical or expressions evaluating to turn the feature or dep on

## Using package activation is okay

Calling the packages "foo" and the features "foo/default" is totally fine and won't hurt anything.  The logic statements generated are easier to read.

## A remaining problem & tradeoff solution

**We don't know which root crates will be built when evaluating one crate.**  The packageFun produces a set of nearly-complete derviations.  If you wanted to build two workspace packages, they would need to activate different sets of features / packages.  This actually would hurt caching and sharing of dependencies.  Features and deps are supposed to be additive and not need to be exclusive (hey RustAnalyzer!  stop enabling both allocators with features!)  The way we're asking user's to pass in `rootFeatures` is definitely just a landmine.  If you don't pass in the default feature for a crate, `expandFeatures` won't insert the root crate "feature" into the list, and anything that depends on that crate won't be turned on.

There may be some nix magic that could tie another knot and obtain a list of workspace crates that are enabled, but 1) it will not be easy to write 2) it doesn't solve anything that shouldn't already just work

The compromise is to always build every dependency as if every package in the workspace will be built.  The better cache sharing should offset the worse initial build of just a single package.  If every workspace crate is always considered enabled, then we can change the simplify logic to instead mark a feature or package required if _any_ workspace package would enable it.  In the end, the Cargo.nix's should be about the same size after fixing feature activation and changing package activation to mean "any package in the workspace."

## The Simplified Tradeoff Implementation

For each root crate, activate no features and resolve dependencies.  If they are active, mark them as activated by the root crate alone (not by its features)
if any dependency or feature is activated by **any root crate**, then mark it as required.  This removes all logic in the Cargo.nix since the feature / dependency does NOT depend on the feature state and **we always assume all packages get built**

### Activated features & deps

For each root crate, resolve dependencies.  Save deps.
For each root crate feature, resolve dependencies.  If dep activated, mark activated_by (root_crate, feature)
These will render in the Cargo.nix as a list of logical or expressions evaluating to turn the feature or dep on

Okay, I think this will work.  Time to code it.

**Comment by psionic-k** [comment]
Fix is at the rough draft level.  Builds the test crate with the following output:

```nix
  cargo2nixVersion = "0.10.0";
  workspace = {
    foo = rustPackages.unknown.foo."0.1.0";
  };
  "unknown".foo."0.1.0" = overridableMkRustCrate (profileName: rec {
    name = "foo";
    version = "0.1.0";
    registry = "unknown";
    src = fetchCrateLocal workspaceSrc;
    features = builtins.concatLists [
      (lib.optional (rootFeatures' ? "foo/default") "default")
      (lib.optional (rootFeatures' ? "foo/elisp") "elisp")
      (lib.optional (rootFeatures' ? "foo/default" || rootFeatures' ? "foo/python") "python")
    ];
  });
```
