### ISSUE TITLE
Add custom packages to `workspaceShell`

### ISSUE THREAD

**Issue by mainrs** [cargo2nix/cargo2nix#220]
I want to add some cargo subcommands to the shell, but after poking around the `overlay/` files it doesn't seem that it is possible. Is that the case?

**Comment by psionic-k** [comment]
Yeah, for now, you can work around by copy-pasting the function definition since it's super short. 

I'll add some arguments.  I think it should just be a pass-through to mkShell, augmented with workspace dependencies

**Comment by psionic-k** [comment]
Fixed in #221 
:santa: :tooth: :fairy:
