### ISSUE TITLE
Make `cargo2nix` available inside devShell.

### ISSUE THREAD

**Issue by mainrs** [cargo2nix/cargo2nix#222]
I've tried multiple things like adding the package inside `buildInputs`, adding it as a package inside my flake but none of them make the `cargo2nix` command available inside my devShell.

I'd ask on GitHub discussions, but those aren't enabled for this repository.

**Comment by psionic-k** [comment]
> I'd ask on GitHub discussions, but those aren't enabled for this repository.

Feel free to sell me on how they are a better structure by pointing me to a good discussion example

If you just need the cargo2nix binary _right now_ then the fastest way is on the readme, `nix run github:/cargo2nix/cargo2nix -- -f`

Very similar command works for `nix shell`

I actually don't recommend tying your cargo2nix binary to your project's dev shell.  When you break your dev shell for a project, it can be tricky to figure out how to bootstrap.  if you need a dev shell binary to fix your dev shell, you're stuck.  Every new project will run into this.  I typically install cargo2nix as a home manager package and then use `nix run` if I want a specific version

I started writing up and example, but I think you're onto something.  Using the flake attributes directly either requires some different work or I didn't expose them correctly.  Neither the overlay nor the defaultPackage are working the way I expect in a 3rd project.

**Comment by psionic-k** [comment]
Okay, here's how you do it:

```nix
        # The workspace defines a development shell with all of the dependencies
        # and environment settings necessary for a regular `cargo build`
        workspaceShell = rustPkgs.workspaceShell {

          # Provide extra tools
          nativeBuildInputs = [
            # from flake inputs (don't recommend using per-repo cargo2nix
            # because it caused bootstrapping issues)
            cargo2nix.defaultPackage.${system}

            # pkgs.hello etc
          ];
        };
```

You can see the paths in `nix flake show` in the cargo2nix repo or by using `nix flake show github:cargo2nix/cargo2nix`

I'm exposing the `overlay` output correctly in #224.  The example will show up in positron-solutions/unixsocks after that PR merges

**Comment by mainrs** [comment]
Thanks! I've read your first comment and I wasn't aware that it would actually cause problems! Thanks for pointing that out :)
