### ISSUE TITLE
How to add rustfmt and clippy to shell

### ISSUE THREAD

**Issue by mainrs** [cargo2nix/cargo2nix#231]
I couldn't find any documentation on how to add `clippy` and `rustfmt` to the `workspaceShell`.

**Comment by psionic-k** [comment]
All of the rust tooling is provided by oxalica/rust-overlay.

I'll add an argument to switch from `minimal` to `default` etc.

The long way is to use the nixpkgs with the overlay already applied and add rust-bin.stable.default to your nativeBuildInputs as extra workspaceShell arguments (workspaceShell accepts all mkShell arguments)

**Comment by psionic-k** [comment]
https://github.com/cargo2nix/cargo2nix/pull/224/commits/e1591efe36f3549c39d4845341f9a994f31f660b

I passed through some more options.

Forgot, if you want, you can make the exact rust toolchain you want using that overlay and pass in `rustToolchain` and it will override everything about `rustVersion` & `rustChannel` etc.  The oxalica readme is pretty easy to figure out.

I added this in #224 and am just having to get back on a Mac before I can fix up a linking issue that showed up

**Comment by mainrs** [comment]
Thanks for clarifying, and sorry for asking so many questions :D
