### ISSUE TITLE
How to selectively build a binary in crate with multiple bins

### ISSUE THREAD

**Issue by yagehu** [cargo2nix/cargo2nix#235]
My crate has multiple cargo bins (one at `src/main.rs` and one under `src/bin`). Is it possible to just build one?

**Comment by psionic-k** [comment]
I'll give this a try sometime in about two weeks.  Take a look at how the bin attribute is constructed, working backward from flake.nix into mkcrate.nix.  My first thought is to see if the multiple bins live in distinct outputs or if they will need to be separated and exposed as attributes.  What do you get if you build a bin attribute like the one in flake.nix now?

**Comment by psionic-k** [comment]
Did you managed to try out your issue?  Is the project published somewhere or can you create a stub representing your problem?

**Comment by psionic-k** [comment]
If they are in one crate, it's not possible to build just one, but you can make a derivation that pulls out just the bin file that you want.  Both should be in `result/bin` or `result-bin/bin` 

See this answer for more details:  https://stackoverflow.com/questions/36604010/how-can-i-build-multiple-binaries-with-cargo

**Comment by psionic-k** [comment]
You can ensure multiple crates by using a workspace.  Use one crate per bin.  Now you get more than one derivation in your workspace and can specifically build just the one you want.  (still recommend using `bin` attribute when installing programs to a nix profile etc)
