### ISSUE TITLE
Unable to reproduce examples/1-hello-world

### ISSUE THREAD

**Issue by au-phiware** [cargo2nix/cargo2nix#244]
Thank you for your good work in the Nix and Rust communities!

I was attempting follow along with the README in the first example, I get encounter this error from the depths of I-don't-know-what:

```
error: builder for '/nix/store/96cd290kyi46f85xh3y81w4xayp7mhjf-cargo-1.60.0-x86_64-unknown-linux-gnu.drv' failed with exit code 127;
       last 10 log lines:
       > Installing component cargo
       > post-installation fixup
       > shrinking RPATHs of ELF executables and libraries in /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu
       > shrinking /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu/bin/cargo
       > shrinking /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
       > gzipping man pages under /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu/share/man/
       > patching script interpreter paths in /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu
       > checking for references to /build/ in /nix/store/6v07viihhfvnfpwdgzx1vjqb3pc6shcz-cargo-1.60.0-x86_64-unknown-linux-gnu...
       > automatically fixing dependencies for ELF files
       > /nix/store/sds4msgr38nfs2zg3fsrd54wv8sndlyx-auto-patchelf-hook/nix-support/setup-hook: line 220: -l: command not found
       For full logs, run 'nix log /nix/store/96cd290kyi46f85xh3y81w4xayp7mhjf-cargo-1.60.0-x86_64-unknown-linux-gnu.drv'.
error: 1 dependencies of derivation '/nix/store/vwjzl8rr6a1pciis74mqsqcnl6slh7y6-rust-minimal-1.60.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rv7s9x2q255lmwm4y97xz5i3b77jqn4j-crate-hello-world-0.1.0.drv' failed to build
```

The `-l: command not found` seems very wrong...

So I cloned this repo and simply ran `nix build` from examples/1-hello-world without any problems (after adjusting the cargo2nix.url), it was only after running `nix flake update` where I encountered the above error.  I tried pinning various things and found that it was an update to oxalica/rust-overlay that causes the issue.  I recognise that there may not be an issue with cargo2nix but, at this point, I'm out of my depth... I thought you should know.

Update: I took it a little further and performed a git-bisect over oxalica/rust-overlay, this first bad commit is https://github.com/oxalica/rust-overlay/commit/44801306a2aa0e9aaa47588d615ce6df4acf18c6.

**Comment by psionic-k** [comment]
Looks like it was this issue:

https://github.com/NixOS/nixpkgs/pull/137886/commits/a7f5e8321e9db6f2cf2f3c6be7ce5cac28bff271

Just need to update the flake definition.  I did so in #224 

Going to close this issue since the workaround / fix is just to use nixpkgs 21.11 instead of 21.05
