### ISSUE TITLE
Providing inputs to `nix build`

### ISSUE THREAD

**Issue by Anton-4** [cargo2nix/cargo2nix#255]
Thanks for working on `cargo2nix` :heart:

I set up a minimal project to demonstrate my issue [here](https://github.com/Anton-4/cargo2nix-deps).
I have a `build.rs` file that calls zig through `std::process::Command`.
When calling `nix build` I'm currently hitting:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:7:14
```
It can't find zig, I know how to provide `zig` for a nix `devShell` inside a flake but I don't know how to provide it for `nix build`.
I'm thinking I need to set `buildInputs` somewhere but I can't figure out the specifics.

**Comment by psionic-k** [comment]
See the overrides example in Readme.  You can just use `buildInputs`.  Here is an example of overriding on the workspace root crate:  https://github.com/cargo2nix/cargo2nix/issues/245

When you add `zig` to the build inputs, it will be on the path, and your build.rs should succeed.

**Comment by Anton-4** [comment]
Thanks :)

I changed
```nix
rustPkgs = pkgs.rustBuilder.makePackageSet {
          rustVersion = "1.60.0";
          packageFun = import ./Cargo.nix;
        };
```
to
```nix
rustPkgs = pkgs.rustBuilder.makePackageSet {
          rustVersion = "1.60.0";
          packageFun = import ./Cargo.nix;
          packageOverrides = pkgs: pkgs.rustBuilder.overrides.all ++ [
            (pkgs.rustBuilder.rustLib.makeOverride {
              name = "cargo2nix-deps";
              overrideAttrs = drv: {
                buildInputs = drv.buildInputs or [ ] ++ [
                  pkgs.zig
                ];
              };
            })
          ];
        };
```
and `nix build` works now.

I have a rust project with multiple crates(workspace members) that use zig, is there a way to make zig available for all crates in the workspace so I don't have to specify overrides for each specific crate? Perhaps it is not recommended to specify buildInputs in an overly broad manner :thinking:

**Comment by psionic-k** [comment]
> works

:tada: 

> make zig available for all crates in the workspace 

#251 will ease the pain.  For now just copy & paste.  It's cruft, but the kind that goes away easily later because it's all in one place.

Closing and picking up remaining concern in #251
