### ISSUE TITLE
overriding libclang on dependency does not propagate to workspaceShell

### ISSUE THREAD

**Issue by stites** [cargo2nix/cargo2nix#256]
When building my project with `cargo build`, I get an error telling me that LIBCLANG_PATH is empty for dependency `minisat`:

```
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/stites/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.42.3/src/lib.rs:1664:31
```

I thought the obvious long term solution would be to override the derivation in the `pkgs.rustBuilder.makePackageSet` function defined in flake.nix: 
```
          packageOverrides = pkgs: pkgs.rustBuilder.overrides.all ++ [
            (pkgs.rustBuilder.rustLib.makeOverride {
              name = "minisat";
              overrideAttrs = old: {
                nativeBuildInputs = old.nativeBuildInputs ++ [ pkgs.llvmPackages.libclang ];
                LIBCLANG_PATH = pkgs.lib.makeLibraryPath [ pkgs.llvmPackages.libclang.lib ];
              };
            })
          ];
        };
```

But I still get the same error. I can fix this issue by adding the path to my `workspaceShell` (ie: `LIBCLANG_PATH = pkgs.lib.makeLibraryPath [ pkgs.llvmPackages.libclang.lib ];`) but I was hoping that cargo2nix would build the dependency in the background and `cargo build` would lookup the cached result. Is this a bug or am I misunderstanding the relationship between cargo and cargo2nix?

**Comment by stites** [comment]
Asked and answered. The extra caching must happen during nix build. Cargo development shouldn't be encapsulated in nix.

**Comment by psionic-k** [comment]
Use `propagatedBuildInputs` and the variable should make it out.  If not, see the `propagateEnv` function to be sure it makes it to the shell.

There's some side effects I don't like about `propagateEnv` that cause #238   If it works fine for you, great.  I'll make sure there's a better replacement if I can't fix it.

Libs don't have host / target offsets since they aren't executed, so no need for `native`
