### ISSUE TITLE
Failed to build cargo2nix on macOS M1

### ISSUE THREAD

**Issue by elliot-midnight** [cargo2nix/cargo2nix#259]
I got this error on macOS M1:

```shell
$ nix --extra-experimental-features nix-command --extra-experimental-features flakes run github:cargo2nix/cargo2nix
error: builder for '/nix/store/ilxs9bblxff1zvac98dmd9dg4an2k8md-crate-cargo-0.61.1.drv' failed with exit code 101;
       last 10 log lines:
       >               /private/tmp/nix-build-crate-cargo-0.61.1.drv-0/cargo-0.61.1/target/aarch64-apple-darwin/release/deps/libcargo-054cdde191e60f08.rlib(str.o)
       >               /nix/store/xh4hy8465nsi1374qqxpkqhs0ij717v9-crate-git2-0.14.4/lib/libgit2.rlib(str.o)
       >           ld: reference to symbol (which has not been assigned an address) _git_libgit2_init_count in '_git_error_last' from /nix/store/ijql275f1slphsf9zkc7idhs5sfdpvha-crate-libgit2-sys-0.13.4+1.4.2/build_script_output/build/libgit2.a(errors.o) for architecture arm64
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >           
       >
       >
       > error: aborting due to previous error
       >
       >
       For full logs, run 'nix log /nix/store/ilxs9bblxff1zvac98dmd9dg4an2k8md-crate-cargo-0.61.1.drv'.
error: 1 dependencies of derivation '/nix/store/jmnwybk8v8rph6w5rwklk0sal9nbpdmf-crate-cargo2nix-0.11.0.drv' failed to build
```

**Comment by psionic-k** [comment]
On Darwin, check out and build with `nixpkgs-unstable` for now.  I'm watching the 22.05 coming out this month to see if it contains the fix for Darwin users.

**Comment by psionic-k** [comment]
Set nixpkgs to release-22.05.  @alarmak says it works.  Pushing update with some other changes.

**Comment by psionic-k** [comment]
use the `--override-input` option.  The actions yml has some examples.  It's something like this:

`nix run cargo2nix/cargo2nix  --override-input nixpkgs github:nixos/nixpkgs/release-22.05`

You'll need a Rustc on the path.  Workaround is to load oxalica overlay as your shell and then use the nix run command.  I'm making a new shell that contains both for bootstrapping.

It's a nice interface, but you will want to get that experimental features flag enabled by default.

**Comment by elliot-midnight** [comment]
Awesome that works. Out of curiosity is there a flakeless way to use this tool? I am sharing with others who only know how to instal Nix and can't configure it.

**Comment by psionic-k** [comment]
The `flake-compat` library is in there.  It's untested and only for convenience for the folks who still "know what they're doing"

**Comment by elliot-midnight** [comment]
Thank you for your help!
