### ISSUE TITLE
Standard install hooks aren't run by default

### ISSUE THREAD

**Issue by CobaltCause** [cargo2nix/cargo2nix#275]
"Standard" according to the [nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#ssec-install-phase). In particular I was trying to add a `postInstall = "mv $bin/bin/something $bin/bin/something-else";` to my package but it didn't work. It took me a while but eventually I found that `cargo2nix`'s `installPhase` doesn't run any of the hooks: https://github.com/cargo2nix/cargo2nix/blob/b57cfe7da3d34274c1db1f4273d42d016147d254/overlay/mkcrate.nix#L317-L330

I found this behavior to be somewhat surprising. I'm not sure whether this was intentional, but I thought I'd point it out.

**Comment by psionic-k** [comment]
Not intentional.  I think the hooks should be run.  Do you want to PR it?

**Comment by CobaltCause** [comment]
Sure!
