### ISSUE TITLE
Unable to build tantivy

### ISSUE THREAD

**Issue by jmpunkt** [cargo2nix/cargo2nix#278]
## Issue

Cargo2nix is not able to build tantivy due to [fastfield_codec](https://github.com/quickwit-oss/tantivy/tree/main/fastfield_codecs). Fastfield\_codec provides a library and a executable version. Tantivy requires fastfield\_codec as a library, thus disabling the optional dependency (which is only required for the binary version).

Cargo2nix successfully detects that certain dependencies are not required for fastfield\_codec, thus omitting (in this case) the crate prettytable. Cargo2nix invokes the command `cargo build` and cargo tries to build the binary and library version. Due to the missing dependency the compilation of the binary fails.

### Bug in Cargo?

Since cargo is invoked (in this particular case) like `cargo build --no-default-features`, cargo should potentially be able to detect that the binary version can not be build. Maybe that is a bug in cargo, but I am not familiar with the internals of cargo.

### Allow lib-only Derivations

Introduce a flag which allows building a crate as library only. The flag can be used as an override. This way, the workflow of fixing broken crates is similar to adding missing dependencies. Already tested a workaround for this solution, which worked fine.

### Detect During Generation Phase

Maybe it is possible to detect this kind of constellation during the generation phase, thus generation different code. However, it is not clear how many other crates use a similar configuration. The previous method seems more flexible overall with less changes required.

## Error Log

Here is the important part of the error log.

```
building
   Compiling fastfield_codecs v0.2.0 (/build/fastfield_codecs-0.2.0)
error[E0463]: can't find crate for `prettytable`
 --> src/main.rs:2:1
  |
2 | extern crate prettytable;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by psionic-k** [comment]
This is #200 

You may be able to work around it by passing something into rootFeatures or just modifying the Cargo.nix.

The changes to the Cargo.nix generation logic required are not trivial

**Comment by psionic-k** [comment]
Can you provide the fastfield_codecs entry from the Cargo.nix?  I want to be sure that it's missing prettytable before calling it the same issue.

**Comment by psionic-k** [comment]
Workaround is to make an override of one of the phases.

Customization of the cargo invocation should be IMO a pretty standard feature of tools like cargo2nix.  Such an override I would consider best placed in `cargo2nix` itself after developed because anyone who uses this crate will have the issue and the cause is a bit unexpected.

How would a normal cargo user handle configuring the build to only make the lib output when using this dependency?  Surely requiring `fastfield_codecs` can be expressed in normal TOML dependency declaration, right?

**Comment by jmpunkt** [comment]
> How would a normal cargo user handle configuring the build to only make the lib output when using this dependency? Surely requiring fastfield_codecs can be expressed in normal TOML dependency declaration, right?

A "normal cargo" user would be everyone which does not use Cargo2nix, I assume. If a user specifies a dependency inside Cargo.toml, then Cargo will build these dependencies as library versions only. No additional configuration required. However, Cargo2nix builds every dependency isolated (a derivation does not know where it is attached to inside the dependency tree), thus `cargo build` detects the `src/main.rs` and tries also building the binary version. We can only force Cargo to stop building the binary version (with the command argument `--lib`).

For example, putting either of the two versions below in your Cargo.toml as a dependency does not build the binary version.
```
fastfield_codecs = { url = "https://github.com/quickwit-oss/tantivy", default-features = false }
```
```
fastfield_codecs = { url = "https://github.com/quickwit-oss/tantivy" }
```
However, in the case of the second version, Cargo additionally pulls and builds the dependencies which are only used by the binary. But it will not build the binary version of fastfield_codecs. Cargo itself does not care if dependencies are not used within the library.

**Comment by psionic-k** [comment]
Got it.  Workaround is definitely to override the phase for just the crate in question.  There's at least one situation where that happens in the provided `overrides.nix`

I will have to add this to "common issues" and provide a specific kind of override for it.

To go deeper, I could make it so that the "out" output is always compiled as lib (if it's not something else) and only the bin outputs compile as bin.

As an interim shorcut, I think an override shortcut #251 should be written for this less common case.  Leaving open until at least some of these are fixed and documented.

Thanks for answering questions.

**Comment by jmpunkt** [comment]
I came up with a workaround which works with the current version of Cargo2nix. Since `src/main.rs` is the main problem here, removing it solves the problem. 

Putting the code below into the overrides builds tantivy.
```nix
(rustBuilder.rustLib.makeOverride {
  name = "fastfield_codecs";
  overrideAttrs = drv: {
    buildPhase =
      ''
        rm src/main.rs
      ''
      + drv.buildPhase;
  };
})
```

Putting this into the global overrides could possible break things, even though I doubt that there is anyone who builds a fastfield_codecs binary. Notice that, if the override would be part of the global overrides, then it would be hard to revert it. This should only be used in local overrides.

So technically the problem is solved and no further steps are required. However, it is still desirable to have a mechanism to adjust the `cargo build` command inside the Cargo2nix.
