### ISSUE TITLE
Support for building `cdylib` crates

### ISSUE THREAD

**Issue by noib3** [cargo2nix/cargo2nix#287]
It seems like only binary crates are currently supported. Would it be possible to also support crates generating C dynamic (or even static) libraries? I have a crate with

```toml
[lib]
crate-type = ["cdylib"]
```

**Comment by quinn-dougherty** [comment]
I'm struggling with a `wasm` build, which is also `lib.crate-type = ["cdylib"]`. I'm not sure if `cargo2nix` is going to support me here.

**Comment by psionic-k** [comment]
> Would it be possible to also support crates generating C dynamic

This should be pretty easy.  Do you have an example I can work with?

The biggest question that comes to mind is if more named outputs in the derivation are needed.
https://github.com/cargo2nix/cargo2nix/blob/release-0.11.0/overlay/mkcrate.nix#L319

The usual situation for outputs is that, while they are created in the build successfully, they also need to be copied to an expected location in one of the nix outputs like "bin" or "out".  See this line:
https://github.com/cargo2nix/cargo2nix/pull/283/commits/db8740f0ea408b867882b478cde16efd6df1f75a

**Comment by psionic-k** [comment]
@quinn-dougherty I believe the issue was that wasm outputs were not being copied into the result.  Recent changes landed in the unstable branch should suppoort the wasm case.

As for the cdylib, I built a trivial crate that resulted in an output on Linux.  I'm not sure what other support is missing.

**Comment by psionic-k** [comment]
I just confirmed on unstable branch that output respects Cargo.toml lib table.  A `cargo new --lib` workspace will reproduce this.

```toml
[lib]
crate-type = ["cdylib"]
```

Output is a *.rlib without the `crate-type` but a *.so with on Linux, reflecting the anticipated outputs of vanilla lib versus cdylib.

Reminder, non-executable output only exists in the `out` output.  By default, calling a crate function will give you a derivation that defaults to `bin` output.  You have to explicitly reference `(crate { }).out` to get the non-binary output.  If you need this in a Nix profile, we should create a new output, `lib` for consumption downstream outside of nix.

Closing.
