### ISSUE TITLE
how to set env vars for _all_ packages

### ISSUE THREAD

**Issue by silky** [cargo2nix/cargo2nix#295]
i'm noticing i can set an env var for a specific package like so:

```
some_thing = ((rustPkgs.workspace.some_thing
{}).overrideAttrs (old: {
  A = "hello";
})).bin;
```

but this doesn't carry over if a different package `some_other_thing` depends _back_ on `some_thing` and that `build.rs` looks for the env var `A`; then it isn't defined.

is there an approach to fix this? i though maybe i could set something for all the workspaces, but i'm not sure how ...

thanks! 🙏🏻  :)

**Comment by silky** [comment]
solved it using the method from here: https://github.com/cargo2nix/cargo2nix/issues/234

**Comment by psionic-k** [comment]
This is an example of environment propagation.  Future readers may also be interested in the `setupHook` or `shellHook`.  In the unstable branch, there's a setupHook example already in overlay/overrides.nix
