### ISSUE TITLE
FR: Respect features in Cargo.toml

### ISSUE THREAD

**Issue by bakhtiyarneyman** [cargo2nix/cargo2nix#300]
Currently, all features seem to be enabled, which means that the result of compilation is not identical to what the Cargo.toml prescribes. Sometimes compilation fails because of this, and this requires the user to give the generated Cargo.nix a manual surgery editing a whole bunch of records in the transitive closure of the offending package. This is a non-ideal user experience.

**Comment by psionic-k** [comment]
#200 Duplicate.  Fix design is under development, using cargo metadata style solution to generate Nix expressions that match cargo behavior.
