### ISSUE TITLE
Moving `devShell` into separate flake.

### ISSUE THREAD

**Issue by mainrs** [cargo2nix/cargo2nix#309]
Hello!

I almost always have a set of common `nativeBuildInputs` that I want to be available when working on Rust projects.

I tried to move these to a separate flake and merge the there defined devShell into my current one. This does not work though. Is there an easy way to do this?

https://github.com/mainrs/flake-templates

```nix
{
  inputs = {
    cargo2nix.url = "github:cargo2nix/cargo2nix/release-0.11.0";
    flake-templates.url = "github:/mainrs/flake-templates";
    flake-templates.inputs.nixpkgs.follows = "cargo2nix/nixpkgs";
    flake-utils.follows = "cargo2nix/flake-utils";
    nixpkgs.follows = "cargo2nix/nixpkgs";
  };

  outputs = inputs: with inputs;
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [cargo2nix.overlays.default];
        };

        rustPkgs = pkgs.rustBuilder.makePackageSet {
          rustVersion = "1.61.0";
          packageFun = import ./Cargo.nix;
        };

        workspaceShell = rustPkgs.workspaceShell // flake-templates.devShells.rust;
      in rec {
        devShells = workspaceShell;
        packages = {
          
        };
      }
    );
}
```

```console
error: value is a function while a set was expected
(use '--show-trace' to show detailed location information)
```

I suspect that the thing returned from `workspaceShell {}` is not a set and thus `//` cannot be used.

**Comment by psionic-k** [comment]
`workspaceShell` is a function.  It will pass almost everything you call it with straight through to the standard Nix `mkShell`.   You can just give the function `nativeBuildInputs` directly.

Since you have a flake, just add the flake's packages.{system}.whatever to `workspaceShell { nativeBuildInputs = [ more stuff ]}`

Also be sure to try unstable.  It has significant upgrades over release-0.11 for workspace shells.

**Comment by mainrs** [comment]
Ah, so I can define something like `flake-templates.packages.rust` and that contains a simple array of `nativeBuildInputs`?

Is there a list of upgrades compared to 0.11?

**Comment by psionic-k** [comment]
> Is there a list of upgrades compared to 0.11?

Not until I cut a new release.  You can check git notes in the log.  It should be good enough.

It will be something like `workspaceShell { nativeBuildInputs = (attrValues myFlake.packages.${system})}`
