### ISSUE TITLE
env var at build time. Cant get it to work

### ISSUE THREAD

**Issue by waalge** [cargo2nix/cargo2nix#328]
I think this is the same as 
https://github.com/cargo2nix/cargo2nix/issues/234
But i can't get this to work. 

I tried to drop into the nix shell as described to 
https://github.com/cargo2nix/cargo2nix#declarative-build-debugging-shell
And i can see the var in `env` but the result of nix build still seems to have thought it did not exist. 

I cant follow the hint of how to use `propogateEnv` or `shellHook` 
Are there any examples to hand?

**Comment by psionic-k** [comment]
I don't quite understand what you need.  Can you unpack your situation a bit more?

**Comment by waalge** [comment]
The project looks up envvars when built. I wanted these set when running nix build. I tried to follow the other example, but it wasn't working for me

This was a while ago - I've switched to using nix-cargo-integration
