### ISSUE TITLE
nix develop && cargo build fails 

### ISSUE THREAD

**Issue by realsnick** [cargo2nix/cargo2nix#340]
Hi,

`nix build` and `nix run` works fine

`nix develop` works however when I run `cargo build` i get the following error:

![image](https://github.com/cargo2nix/cargo2nix/assets/1440852/0e5f472a-eb99-4009-8459-0840a406b163)

**Comment by realsnick** [comment]
also the nix develop creates an impure env...not sure why

**Comment by realsnick** [comment]
i was able to have `cargo build` works by doing the following:

```nix-shell -p systemd pkgconfig ```

is there a way to add it to the flake.nix ? sorry still new to the syntax

**Comment by psionic-k** [comment]
`nix develop` isn't in CI.  It must have bit-rotted.

The way dependencies are made available downstream is through the overrides adding them to each crate that needs some.  You can see overrides.nix for how they are originally added.

How they get propagated out to each attribute depends, but the nix develop and nix build are pretty closely related, meaning they shouldn't fail independently, but they obviously have in this case.

**Comment by realsnick** [comment]
was able to solve it with

```
        # create the workspace & dependencies package set
        rustPkgs = pkgs.rustBuilder.makePackageSet {
          rustVersion = "1.73.0";
          packageFun = import ./Cargo.nix;

          packageOverrides = pkgs: pkgs.rustBuilder.overrides.all ++ [
            (pkgs.rustBuilder.rustLib.makeOverride {
              name = "libc";
              overrideAttrs = drv: {
                propagatedNativeBuildInputs = drv.propagatedNativeBuildInputs or [ ] ++ [
                  pkgs.systemd
                  pkgs.pkg-config
                ];
              };
            })
          ];
        };
```
