### ISSUE TITLE
Is there a way to use Fenix with Cargo2Nix

### ISSUE THREAD

**Issue by RGBCube** [cargo2nix/cargo2nix#342]
As the title says, I want to use Fenix with Cargo2Nix but there doesn't seem to be a documented way. The reason I want to is to use the latest Rust release which Cargo2Nix doesn't have. Also nightly.

Is there a way? Crane supports it, but I do not want to use crane because of the incremental compilation for dependencies provided by Cargo2Nix.

**Comment by psionic-k** [comment]
I'm working on something called Fenix.  Which Fenix are you talking about?

Cargo2nix can use whatever Rust toolchain you want.  See the arguments:
https://github.com/cargo2nix/cargo2nix/blob/release-0.11.0/flake.nix#L38-L41

Just update the rust-overlay by providing your own.

**Comment by RGBCube** [comment]
Oh, I was not aware of the toolchain parameter. Thanks.

I'm referring to the Nix helper for rust toolchains when I mean Fenix
