### ISSUE TITLE
Check version compatibility between cargo2nix and Cargo.nix

### ISSUE THREAD

**Issue by snawaz** [cargo2nix/cargo2nix#51]
It'd be good to ensure that the imported `cargo2nix` is compatible with `Cargo.nix` of the project.

- `Cargo.nix` exposes [`cargo2nixVersion`][1] (the version of `cargo2nix` which was used to generate this file). We could use this to ensure that the imported `cargo2nix` version is compatible, else it should fail with a good error message.

[1]: https://github.com/tenx-tech/cargo2nix/pull/50#discussion_r358304625

**Comment by ebkalderon** [comment]
Just to clarify, when you say "imported `cargo2nix`," I assume you mean the imported `cargo2nix` overlay?

I think this is definitely doable! It would mean that `makePackageSet` would need to check the version specified by `cargo2nixVersion` against its own and `throw` an error if they are incompatible. With that said, I would much prefer it if we didn't use a straight string equality check for this task and instead checked for semantic versioning compatibility between them. Perhaps something like [`lib.versionAtLeast`](https://github.com/NixOS/nixpkgs/blob/master/lib/strings.nix#L473) or [`builtins.compareVersions`](https://nixos.org/nix/manual/#ssec-builtins) could help here.

**Comment by snawaz** [comment]
> Just to clarify, when you say "imported cargo2nix," I assume you mean the imported cargo2nix overlay?

Yes, the overlays &mdash; the nix stuff the clients could use.

**Comment by psionic-k** [comment]
I could be wrong, but I don't think there's anything left to do on this issue
